### ISSUE TITLE
False positive: trailing comma for functions in if clause

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-lint-trailing_comma-check#4]
See: https://github.com/voxpupuli/puppet-archive/pull/264

```
  if $file_path !~ Stdlib::Compat::Absolute_path {
    fail("archive::artifactory[${name}]: \$name or \$archive_path must be an absolute path!")
  }
```

results into an error:

```
trailing_comma:WARNING:missing trailing comma after last element
```

**Comment by ffrank** [comment]
So, the plugins suspects a hash literal here?

What's the token type of `Stdlib::Compat::Absolute_path`?

**Comment by natemccurdy** [comment]
Hitting this same bug with the following (very similar) code.

The error messages says that the fault is on line 2 (the fail statement) even though it's really on line 1:

```puppet
if "${conf_prefix}${conf_suffix}" !~ Stdlib::Unixpath {
  fail("The path to the conf dir is not a valid Unix path: ${conf_prefix}${conf_suffix}")
}
```
