### ISSUE TITLE
Invalid handling of heredoc strings

### ISSUE THREAD

**Issue by joshuaspence** [voxpupuli/puppet-lint-trailing_comma-check#8]
Currently this `puppet-lint` rule complains about the following syntax:

```
file { '/tmp/test.txt':
  ensure  => 'file',
  content => @(EOT),
    Hello
    World
  EOT
}
```

Adding a comma after the trailing heredoc delimiter (as the linter rule suggests), causes an invalid syntax though.

**Comment by ekohl** [comment]
Fixed in #10
